name: sql-fundamentals
root: <%= Dir.pwd %>

windows:
  - frontend:
      layout: main-vertical
      panes:
        - vim
        - docker-compose up
        - docker-compose exec sql_fundamentals psql -U postgres
